### ISSUE TITLE
Node Comments

### ISSUE THREAD

**Issue by kmcgrady** [rsstdd/learn_web_dev#4]
I’m going to preface this with, if you read this is not true, feel free to ignore. A lot of these ideas are my hunch. I honestly don’t know much about libuv or really the inner workings of V8.

"Node.js' performance is attributed to being single-threaded, which bypasses thread context switching.” I’m not sure this is true. It does not have to worry about the context switching, but I think the true benefit is that it’s MUCH easier to reason about. Parallel applications are usually faster (they are performing tasks in parallel) but there is a much bigger complexity to manage.

Asynchronous can be expanded to reading/writing files, or timers, etc and other tasks. It’s really a term for a non-blocking task.

**Comment by rsstdd** [comment]
Thanks for the feedback! I've updated accordingly.
